CREATE TABLE users (
	name VARCHAR(50) NOT NULL,
	surname VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL PRIMARY KEY,
	password VARCHAR(100) NOT NULL,
	pubkey INTEGER NOT NULL,
	exponent INTEGER NOT NULL
);

CREATE TABLE privkeys (
    email VARCHAR(50) NOT NULL PRIMARY KEY,
    privkey INTEGER NOT NULL
);

CREATE TABLE mails (
	sender VARCHAR(50) NOT NULL REFERENCES users(email),
	receiver VARCHAR(50) NOT NULL REFERENCES users(email),
	subject VARCHAR(100) NULL,
	body TEXT NOT NULL,
	"timestamp" TIMESTAMP NOT NULL PRIMARY KEY,
	digital_signature TEXT DEFAULT NULL
);